### ISSUE TITLE
Post-GoLive Fixes Needed Checklist (content)

### ISSUE THREAD

**Issue by Gonzalo-CG** [hlxsites/vg-roadchoice-com#191]
**This issue is intended to group every content detail that needs fixing observed during GoLive.**

- [x] When hovering the "SUBMIT" button present on the forms in "/contact-us" and "/subscribe", the cursor doesn't change to a hand like it should.
- [x] There is no "Thank You" page created for the form submit. It should be created on Sharepoint as "/subscribe/thank-you.docx"
<img src="https://github.com/hlxsites/vg-roadchoice-com/assets/139977780/8bc4699c-fa67-4a2e-abf5-68130af60198" width="50%">

- [x] When opening a PDF file, the favicon of the window showing the PDF viewer is an Adobe icon, instead of the RoadChoice icon. Is this even configurable?
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/139977780/64def696-095c-4b07-b256-3df921e51eb5)

- [x] Check PDF links on PDPs. For example, the "BATTERIES CATALOG (2)" on this [page](https://www.roadchoice.com/parts?category=batteries&sku=27FCRC) leads to a 404.
- [x] Wrong catalogs are shown on some parts. For example on part [ALT11076](https://www.roadchoice.com/parts?category=alternators&sku=ALT11076) (alternator) the catalog table shows air disc brakes PDFs.
<img src="https://github.com/hlxsites/vg-roadchoice-com/assets/139977780/b6a473d6-1221-4442-8d7e-ce39966a9a63" width="50%">

**Comment by girishdigrajkar** [comment]
- [ ] When clicked on  'DOWNLOAD OUR UPDATED BRAND ASSETS HERE'   button takes us to link.com/in ;  It should be set to correct content
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/e070670c-c9c2-428e-8189-3d896896974f">

**Comment by girishdigrajkar** [comment]
- [ ]  Email updates received from roadchoice has incorrect social media (Twitter/X) icon.

![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/9b98dfe2-8a56-4a2a-802a-892cbf80a1c8)

**Comment by girishdigrajkar** [comment]
- [ ] Content missing in sharepoint for multiple parts
e.g.   
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/d682e3dd-4495-44ee-a659-3ca24f5a70db)

**Comment by janedbarra** [comment]
Hi @girishdigrajkar I have checked the product data file for this subcategory and everything appears to be there. I also checked the master attribute file and the filter option and couldn't see an issue. Looks like a bug? 

I did notice it was missing from the category navigation; however, the link is giving a 404 error. Is this the correct link to use? https://www.roadchoice.com/part-category/?category=parts-kits

**Comment by manuel-vara** [comment]
@jonatan-lledo-netcentric FYI, please check Jane's comments above and related product data files to determine the root cause of the issue.

**Comment by jonatan-lledo-netcentric** [comment]
> Hi @girishdigrajkar I have checked the product data file for this subcategory and everything appears to be there. I also checked the master attribute file and the filter option and couldn't see an issue. Looks like a bug?

if the file is not there, I don't think so

> 
> I did notice it was missing from the category navigation; however, the link is giving a 404 error. Is this the correct link to use? https://www.roadchoice.com/part-category/?category=parts-kits

The URL is correct, at least the pattern, but I checked the sharepoint looking for a file named _`rc-parts-kits.xlsx`_ and is not in _`/product-data`_ so, even if the subcategory is correct, the data is not there

**Comment by janedbarra** [comment]
Ah it was saved as rc-hvac-kits

**Comment by jonatan-lledo-netcentric** [comment]
> Ah it was saved as rc-hvac-kits

so, any parts-kits category that is in any of the 2 search files can be updated to hvac-kits? @janedbarra

**Comment by DanielaPedrochevd** [comment]
@Kannan-CM the subscribe button is part of an iframe so it has to be updated on your side. Please let us know if it will be a spillover.

**Comment by Kannan-CM** [comment]
On the Old site we did not have it in an iFrame:
https://cm.roadchoice.com/subscribe

Wonder if we can inject it like the Eloqua forms on Mack Trucks, which are not in and iFrame..

**Comment by jonatan-lledo-netcentric** [comment]
I changed the status to _On Hold_ because we have the focus on redesign. As soon we have more time, we can resume the fixing development of this ticket

**Comment by mollyaljenkins** [comment]
Closed as completed.
