### ISSUE TITLE
Post-GoLive Fixes Needed Checklist (Code)

### ISSUE THREAD

**Issue by girishdigrajkar** [hlxsites/vg-roadchoice-com#207]
Tasks:

- [x] subcategory  [GD] 27 Oct : Works fine now 
- [ ] breadcrumb
- [ ] cookie btn
- [x]  part number label [GD] 31 Oct: Works fine now 
- [x]  Mobile: Resources link navigation not set [GD] 31 Oct: Works fine now 
- [ ] Mobile: Hamburger menu footer link ' ALL-MAKES CATALOG' displays 404 page

1 - [ ]  Subcategory page 'show more' link is not displayed 
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/dd31bff8-845d-43f8-b1f6-1800cbd29a90">

2 - [ ] Clicking on Category breadcrumb of subcategory page shows 404 page
<img width="1792" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/f048cfde-7e6a-4297-a82c-2fddfd1534f1">

3 - [ ]  Cookie preference center is not navigating to correct page
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/fad773c4-0a11-425a-922c-3f40f9b972d5)

4 - [ ]  Part Number Label is not as expected
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/0cd5a330-07d2-4028-b20f-2c8d518d9ba4)

5 - [ ] Mobile: Resources link navigation not set
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/e02d652c-e434-48ee-af3e-108f9301453e)

6 - [ ] Mobile: Hamburger menu footer link ' ALL-MAKES CATALOG' displays 404 page
<img width="491" alt="image" src="https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/d101e961-7adf-4854-bd8f-5c43c0c51902">

**Comment by girishdigrajkar** [comment]
Validated and subcategories related issue is fixed successfully.

**Comment by jonatan-lledo-netcentric** [comment]
in mobile, all catalogs link has been updated, swapping the nav file to anew one with the correct link @girishdigrajkar

**Comment by jonatan-lledo-netcentric** [comment]
breadcrumb Fix by #213 
cookie btn Fix #210 
@girishdigrajkar

**Comment by girishdigrajkar** [comment]
Hi @jonatan-lledo-netcentric 
**Breadcrumb**:
Issue is fixed for all the scenarios except below one:
Getting issue for search >>
![image](https://github.com/hlxsites/vg-roadchoice-com/assets/125972657/ce780f0a-a3a7-47ad-8359-d29e6157c52f)

**Cookie btn:**
Getting same result and cookie preference center does not open the cookie settings page.

**Comment by girishdigrajkar** [comment]
> > Hi @jonatan-lledo-netcentric **Breadcrumb**: Issue is fixed for all the scenarios except below one: Getting issue for search >>
> 
> Let me add a fix for that...
> 
> > **Cookie btn:** Getting same result and cookie preference center does not open the cookie settings page.
> 
> This is the expected behaviour in a develope environment URL. You need to tested in a production one such as `.live` or in `roadchoice` domain

.live and production too has the same behaviour for cookie related issue

**Comment by jonatan-lledo-netcentric** [comment]
> .live and production too has the same behaviour for cookie related issue

the cookie page was not published, only previewed. now is also published. please, can you retested again? thanks @girishdigrajkar

**Comment by jonatan-lledo-netcentric** [comment]
the search item in breadcrumb is fixed @girishdigrajkar

**Comment by girishdigrajkar** [comment]
Validated and able to get correct results
