### ISSUE TITLE
Go Live Checklist: Road Choice Canada

### ISSUE THREAD

**Issue by ZoeBeykirch** [hlxsites/vg-roadchoice-com#259]
### Description:
Create dedicated multi-language websites for the Canadian market under Road Choice, supporting both French and English versions. These separate tickets should help streamline the development and testing processes for each market site while ensuring clarity in responsibilities and outcomes.

Related tickets: 
https://github.com/hlxsites/vg-roadchoice-com/issues/222
https://github.com/hlxsites/vg-roadchoice-com/issues/258

### Acceptance Criteria:

- [x] Set up SharePoint folders specific to Canada. - [vg-roadchoice-ca](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/[vg-roadchoice-ca](https://adobe.sharepoint.com/:f:/r/sites/HelixProjects/Shared%20Documents/sites/VolvoGroup/vg-roadchoice-ca?csf=1&web=1&e=M6k40E)?csf=1&web=1&e=M6k40E)
- [ ] Utilize the USA website structure as a template for the Canadian site.
- [ ] Ensure capability to use all component blocks from the USA site.
- [ ] There is an English version of the site
- [ ] There is a French Canadian version of the site
- [ ] Hardcoded items 
- [ ] Coordinate with DNS configurations for the domain (https://www.roadchoice.ca/fr-ca/).
- [ ] QA team: Begin testing the new Road Choice Canada website preview (https://main--roadchoice-ca--volvogroup.aem.page/).
- [ ] Resolve any functional bugs to ensure full website functionality.
- [ ] Approval from @janedbarra and team to go live

**Comment by BeckyMedlin** [comment]
@janedbarra Please review this go-live checklist and advise if anything else needs to be added. Thank you!

**Comment by janedbarra** [comment]
@BeckyMedlin - This looks good to me, thanks!

**Comment by ZoeBeykirch** [comment]
Canada should be prioritized to go live before Mexico market if they both can't be launched in the same sprint.

**Comment by BeckyMedlin** [comment]
@janedbarra Any objection to removing the Dealer Locator translation work https://github.com/hlxsites/vg-roadchoice-com/issues/233 from this acceptance criteria? We can plan for this separately and will reduce the complexity of this ticket.

**Comment by janedbarra** [comment]
@BeckyMedlin, yes that is fine. We can launch w/o the dealer locator and have that in a separate ticket.

**Comment by mollyaljenkins** [comment]
Issue to be broken down in refinement
